title   kiro install medium (%ARCH%, UEFI, NVIDIA proprietary, auto-detect)
sort-key 02b
linux   /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux-cachyos
initrd  /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux-cachyos.img
options archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID% cow_spacesize=10G copytoram=n driver=nonfreechwd nvidia nvidia-drm.modeset=1 nouveau.modeset=0 radeon.modeset=1 i915.modeset=1 module_blacklist=pcspkr,nouveau nvme_load=yes quiet splash loglevel=3 no_timer_check
